apiVersion: v1
kind: Namespace
metadata:
  name: loadgen
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loadgen-config
  namespace: loadgen
data:
  EVENTS_PER_SEC: "50"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_TOPIC: "events-in"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: loadgen
          image: flink-elastic/loadgen:0.1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: loadgen-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
